name: ad99py
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - dask
  - distributed
  - ipykernel
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - scipy
  - xarray
  - dask-jobqueue
  - gcsfs
  - zarr
  - joblib
  - tqdm
  - pytest
  - ffmpeg
  - xesmf
  - cfgrib
  - h5py

